baseURL = 'https://portfoliotayel.onrender.com'
languageCode = 'fr'
title = 'Portfolio de Tayel'
theme = 'ananke'
sectionPagesMenu = 'main'

[params]
site_logo = "images/TayelLogo.png"

[module]
[[module.mounts]]
source = 'static'
target = 'static'
